/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ["Manrope", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
      },
      colors: {
        primary: "#00450d",
        "primary-container": "#065f18",
        "on-primary": "#ffffff",
        "on-primary-container": "#86d881",
        "inverse-primary": "#88d982",
        "primary-fixed-dim": "#88d982",
        secondary: "#4c616c",
        "secondary-container": "#cfe6f2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#526772",
        "secondary-fixed": "#cfe6f2",
        "on-secondary-fixed": "#071e27",
        "on-secondary-fixed-variant": "#354a53",
        tertiary: "#00433b",
        "tertiary-container": "#005d52",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#79d6c5",
        "tertiary-fixed": "#97f3e2",
        "on-tertiary-fixed": "#00201b",
        "on-tertiary-fixed-variant": "#005047",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "surface-container": "#eeeeee",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#42493f",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "outline-variant": "#c0c9bb",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#410002",
        scrim: "#000000",
        shadow: "#000000",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
      },
    },
  },
  plugins: [],
};
